### ISSUE TITLE
"Auto download test - getArtifactTest" test failed with error "Could not start a new session. Response code 500"

### ISSUE THREAD

**Issue by okamara** [zebrunner/carina-demo#357]
Steps:
1. Start Web regression
2. Test "Auto download test - getArtifactTest" failed in "Carina Demo Tests - Auto Download" job with error message:

org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: New session attempts retry count exceeded...

`org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: New session attempts retry count exceeded...
expand_less
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: New session attempts retry count exceeded
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: '2567e508708c', ip: '172.19.0.23', os.name: 'Linux', os.arch: 'amd64', os.version: '5.19.0-1022-aws', java.version: '17.0.6'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: firefox, enableLog: true, enableVideo: true, moz:debuggerAddress: true, moz:firefoxOptions: {profile: UEsDBBQACAgIAPSEhVYAAAAAAAA...}, provider: zebrunner}], desiredCapabilities=Capabilities {acceptInsecureCerts: true, browserName: firefox, enableLog: true, enableVideo: true, moz:debuggerAddress: true, moz:firefoxOptions: {profile: UEsDBBQACAgIAPSEhVYAAAAAAAA...}, provider: zebrunner}}]
Capabilities {}
 at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:144)
 at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:102)
 at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
 at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
 at com.zebrunner.carina.webdriver.listener.EventFiringSeleniumCommandExecutor.execute(EventFiringSeleniumCommandExecutor.java:58)
 at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:547)
 at org.openqa.selenium.remote.RemoteWebDriver.startSession$original$LILWOevE(RemoteWebDriver.java:242)
 at org.openqa.selenium.remote.RemoteWebDriver.startSession$original$LILWOevE$accessor$muQhNYMp(RemoteWebDriver.java)
 at org.openqa.selenium.remote.RemoteWebDriver$auxiliary$iAEHR5BE.run(Unknown Source)`

**Comment by akamarouski** [comment]
https://github.com/aerokube/selenoid/issues/1301?ysclid=lgdkh911ko592677907

**Comment by akamarouski** [comment]
wontfix
